packages:
  - examples/*
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@nuxt/devalue': ^2.0.2
  '@types/fs-extra': ^11.0.4
  '@types/html-minifier-terser': ^7.0.2
  '@types/jsdom': ^21.1.7
  '@types/yargs': ^17.0.33
  '@unhead/dom': ^1.11.15
  '@unhead/vue': ^1.11.15
  '@vitejs/plugin-vue': ^5.2.1
  beasties: ^0.2.0
  bumpp: ^9.9.3
  cross-env: ^7.0.3
  eslint: ^9.17.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fs-extra: ^11.2.0
  html-minifier-terser: ^7.2.0
  html5parser: ^2.0.2
  jsdom: ^25.0.1
  kolorist: ^1.8.0
  p-queue: ^8.0.1
  pinia: ^2.3.0
  prettier: ^3.4.2
  rollup: ^4.30.1
  tsup: ^8.3.5
  typescript: 5.6.3
  unbuild: ^3.2.0
  unplugin-vue-components: ^28.0.0
  unplugin-vue-markdown: ^28.0.0
  vite: ^6.0.7
  vite-plugin-pages: ^0.32.4
  vite-plugin-pwa: ^0.21.1
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  yargs: ^17.7.2
